export const UserTagKeys = {
  accentColor: 'csui.user.accent-color',
  askToCreateVm: 'csui.user.ask-to-create-vm',
  askToCreateVolume: 'csui.user.ask-to-create-volume',
  savePasswordForAllVms: 'csui.user.save-password-for-all-vms',
  firstDayOfWeek: 'csui.user.first-day-of-week',
  lang: 'csui.user.lang',
  lastVmId: 'csui.user.last-vm-id',
  primaryColor: 'csui.user.primary-color',
  sessionTimeout: 'csui.user.session-timeout',
  sshDescription: 'csui.user.ssh-description',
  showSystemTags: 'csui.user.show-system-tags',
  timeFormat: 'csui.user.time-format',
  theme: 'csui.user.theme',
  navigationOrder: 'csui.user.navigation-order',
  serviceOfferingClass: 'csui.service-offering.class',
  serviceOfferingParam: 'csui.service-offering.param',
};
