export const virtualMachineTagKeys = {
  color: 'csui.vm.color',
  description: 'csui.vm.description',
  group: 'csui.vm.group',
  agreementAccepted: 'csui.vm.agreement-accepted',
  passwordTag: 'csui.vm.password',
  loginTag: 'csui.vm.login',
  authModeToken: 'csui.vm.auth-mode',
  httpProtocolToken: 'csui.vm.http.protocol',
  httpPortToken: 'csui.vm.http.port',
  httpPathToken: 'csui.vm.http.path',
  httpLoginToken: 'csui.vm.http.login',
  httpPasswordToken: 'csui.vm.http.password',
  sshLoginToken: 'csui.vm.ssh.login',
  sshPasswordToken: 'csui.vm.ssh.password',
  sshPortToken: 'csui.vm.ssh.port',
};
