export const userTagKeys = {
  askToCreateVM: 'csui.user.ask-to-create-vm',
  askToCreateVolume: 'csui.user.ask-to-create-volume',
  savePasswordForAllVMs: 'csui.user.save-password-for-all-vms',
  keyboardLayoutForVms: 'csui.user.vm-keyboard-layout',
  firstDayOfWeek: 'csui.user.first-day-of-week',
  lang: 'csui.user.lang',
  lastVMId: 'csui.user.last-vm-id',
  sessionTimeout: 'csui.user.session-timeout',
  showSystemTags: 'csui.user.show-system-tags',
  timeFormat: 'csui.user.time-format',
  theme: 'csui.user.theme',
  computeOfferingParam: 'csui.user.compute-offering.param',
  vmLogsFilter: 'csui.user.vm-logs',
  vmLogsShowLastMessages: 'csui.user.vm-logs-show-last-messages',
  vmLogsShowLastMinutes: 'csui.user.vm-logs-show-last-minutes',
  sidebarWidth: 'csui.user.sidebar-width',
};
