export enum VmActions {
  START = 'start',
  STOP = 'stop',
  REBOOT = 'reboot',
  RESTORE = 'restore',
  DESTROY = 'destroy',
  EXPUNGE = 'expunge',
  RECOVER = 'recover',
  RESET_PASSWORD = 'resetPasswordFor',
  CONSOLE = 'console',
  CHANGE_SERVICE_OFFERING = 'changeServiceOffering',
  WEB_SHELL = 'webShell',
  PULSE = 'pulse',
  ACCESS = 'access',
  CREATE_VM_LOGS_TOKEN = 'createVmLogsToken',
  INVALIDATE_VM_LOGS_TOKEN = 'invalidateVmLogsToken',
}
